---

- name: Allow all access to TCP calico needed ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
  - '179'
  - '5473'

- name: Allow all access to UDP calico needed ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  with_items:
  - '4789'

- name: download lua and haproxy source tarballs
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: "{{ kubernetes_project_dir }}/"
  delegate_to: localhost
  connection: local
  run_once: true
  become: no

- name: apply network plugin
  shell: kubectl apply -f {{ kubernetes_project_dir }}/calico.yaml --kubeconfig={{ kubernetes_project_dir }}/master/admin.conf
  delegate_to: localhost
  connection: local
  run_once: true
  become: no