- name: copy mongod key
  copy:
    src: ./files/redis.conf
    dest: /etc/redis/redis.conf
    mode: 0640
    owner: redis
    group: redis
  tags: config

- name: Restart redis after change config
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: redis-server
  tags: config