---
# tasks file for haproxy

- name: create haproxy downloads directory
  file:
    path: "{{ haproxy_local_dir }}/haproxy/downloads/"
    state: directory
  delegate_to: localhost
  connection: local
  run_once: true
  become: no

- name: download lua and haproxy source tarballs
  get_url:
    url: "{{ item }}"
    dest: "{{ haproxy_local_dir }}/haproxy/downloads/"
  with_items:
  - https://www.lua.org/ftp/lua-{{ haproxy_lua_version }}.tar.gz
  - http://www.haproxy.org/download/2.2/src/haproxy-{{ haproxy_version }}.tar.gz
  delegate_to: localhost
  connection: local
  run_once: true
  become: no

- name: unpack lua and haproxy source tarballs
  unarchive:
    src: "{{ haproxy_local_dir }}/haproxy/downloads/{{ item }}"
    dest: $HOME
  with_items:
  - lua-{{ haproxy_lua_version }}.tar.gz
  - haproxy-{{ haproxy_version }}.tar.gz

- name: install haproxy build dependencies
  apt:
    name:
    - build-essential
    - libssl-dev
    - libsystemd-dev
    - libpcre3-dev
    - zlib1g-dev
    state: present

- name: sysctl for haproxy
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    state: present
    ignoreerrors: yes
    sysctl_set: yes

- name: create haproxy group
  group:
    name: haproxy
    gid: 188
    state: present

- name: create haproxy user
  user:
    name: haproxy
    uid: 188
    group: haproxy
    home: /var/lib/haproxy
    shell: /sbin/nologin
    comment: HAProxy Load Balancer
    state: present

- name: create haproxy etc directory
  file:
    path: /etc/haproxy
    state: directory

- name: copy haproxy unit file
  copy:
    src: usr_lib_systemd_system_haproxy.service
    dest: /usr/lib/systemd/system/haproxy.service

- name: create haproxy chroot and dev directory
  file:
    path: /var/lib/{{ item }}
    state: directory
    owner: haproxy
    group: haproxy
  with_items:
  - haproxy
  - haproxy/dev

- name: build lua from source
  shell: /bin/make linux
  args:
    chdir: $HOME/lua-{{ haproxy_lua_version }}

- name: build haproxy from source
  shell: |
    /bin/make -j $(nproc) TARGET=linux-glibc USE_OPENSSL=1 USE_ZLIB=1 USE_LUA=1 \
    LUA_INC=../lua-{{ haproxy_lua_version }}/src LUA_LIB=../lua-{{ haproxy_lua_version }}/src \
    USE_PCRE=1 USE_SYSTEMD=1 EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o" \
    && make install PREFIX=/usr
  args:
    chdir: $HOME/haproxy-{{ haproxy_version }}

- name: generate openssl dhparam for haproxy
  openssl_dhparam:
    path: /etc/haproxy/haproxy-dhparam-{{ haproxy_dhparam_size }}.pem
    mode: 0400
    size: "{{ haproxy_dhparam_size }}"

- name: copy haproxy config
  template:
    src: etc_haproxy_haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0640


- name: Allow all access to tcp port haproxy frontend port
  ufw:
    rule: allow
    port: "{{ haproxy_frontend_port }}"
    proto: tcp

- name: start haproxy
  systemd:
    daemon_reload: yes
    name: haproxy
    enabled: yes
    state: started

- name: delete unneded haproxy files from remote
  file:
    path: $HOME/{{ item }}
    state: absent
  with_items:
  - lua-{{ haproxy_lua_version }}
  - haproxy-{{ haproxy_version }}

- name: wait for haproxy dependencies stop
  pause:
    prompt: "Waiting until dpkg stops"
    minutes: "1"

- name: uninstall haproxy build dependencies
  apt:
    name:
    - build-essential
    - libssl-dev
    - libsystemd-dev
    - libpcre3-dev
    - zlib1g-dev
    state: absent